apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: userserviceapp-prod
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: https
      port: 8081
      targetPort: 8081
      nodePort: 30081