apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: userserviceapp-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "true"
            - name: MSSQL_SA_PASSWORD
              value: Pass@word
          image: mcr.microsoft.com/mssql/server:2022-latest
          name: db
          ports:
            - containerPort: 1433
              protocol: TCP
              name: mssql
      restartPolicy: Always