version: '3.9'

volumes:
    sqldb-data:
  
services:

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: UserServiceAppDB
    environment:
      - ACCEPT_EULA=true
      - MSSQL_SA_PASSWORD=Pass@word
    ports:
      - '1433:1433'
    volumes:
    - sqldb-data:/var/opt/mssql