name: CI
on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  DOTNET_VERSION: "9.x"
  
jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
     
      - name: dotnet test
        run: dotnet test ./src/UserServiceApp.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./src/UserServiceApp.API/UserServiceApp.API.csproj --configuration Release -o artifacts

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: useserviceapp-artifact
          path: artifacts/

  deploy_dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: useserviceapp-artifact
          path: artifacts/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
            app-name: app-userserviceapp-glebnichyparovich-dev
            package: artifacts/
    
